/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab2;

import COMP3111.Lab2.ex1.Book;
import COMP3111.Lab2.ex1.Computer;
import COMP3111.Lab2.ex1.MobileComputer;

public class Library {
    public static void main(String[] args) {
        final String array[] = {"Basic Java", "Advanced Java", "Guru Java"};
        Book b = new Book(array);

        int k = 2;
        System.out.println("The title of Chapter " + k + " is " + b.getChapter(k-1));
        String[] anotherArray = b.getChapters();

        System.out.println("There are " + anotherArray.length + " chapters");
        System.out.println(java.util.Arrays.toString(anotherArray));

        Computer a = new MobileComputer();
        for (int i = 0; i< 10; i++)
            a.work();

    }


    public boolean someLibraryMethod() {
        return true;
    }
}
